name: b4
base: core22
version: 0.12.3
summary: A tool to work with public-inbox and patch archives
description: |
  This is a helper utility to work with patches and pull requests made available
  via a public-inbox archive like lore.kernel.org. It is written to make it
  easier to participate in a patch-based workflows, like those used in the Linux
  kernel development.

  The name “b4” was chosen for ease of typing and because B-4 was the precursor
  to Lore and Data in the Star Trek universe.

  Full documentation is available on https://b4.docs.kernel.org/.
license: GPL-2.0-or-later
website: https://git.kernel.org/pub/scm/utils/b4/b4.git/about/
issues: https://github.com/alexmurray/b4-snap/issues

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: classic

apps:
  b4:
    command: bin/b4

parts:
  b4:
    plugin: python
    source: https://git.kernel.org/pub/scm/utils/b4/b4.git
    stage-packages:
      - python3
      - python3.10
      - python3.10-venv
      - libpython3.10-minimal
      - libpython3.10-stdlib
